Repository dextel2/core-server, pull requests merged in 2023-10, with the labels that each got.

#30 update License
  LICENSE.md
Labels: hacktoberfest, hacktoberfest-accepted

#28 update port
  server.js
Labels: hacktoberfest, hacktoberfest-accepted

#29 Patch 1 k
  src/data/products.json
Labels: hacktoberfest, hacktoberfest-accepted

#31 added checks for undefined
  controllers/admin.js
  controllers/shop.js
Labels: hacktoberfest, hacktoberfest-accepted

#33 added check for product if found or not
  views/shop/product-detail.ejs
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#32 css changes
  public/css/cart.css
  public/css/main.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#34 css changes
  public/css/forms.css
  public/css/product.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
